import { DM_Sans } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";

const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Castaway",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
